config/routes.rb
Rails.application.routes.draw do
  resources :past_situations
  resources :new_situations
  resources :ideal_outcomes
  resources :past_outcomes
  resources :past_outcomes
  resources :recommended_decisions
  resources :user_decisions
  resources :new_situations
  resources :past_situations
  resources :users

end

app/models/ideal_outcome.rb
class IdealOutcome < ActiveRecord::Base
  belongs_to :new_situation
  belongs_to :recommended_decision
end

app/controllers/ideal_outcomes_controller.rb
class IdealOutcomesController < ApplicationController
  before_action :set_ideal_outcome, only: [:show, :edit, :update, :destroy]

  # GET /ideal_outcomes
  # GET /ideal_outcomes.json
  def index
    @ideal_outcomes = IdealOutcome.all
  end

  # GET /ideal_outcomes/1
  # GET /ideal_outcomes/1.json
  def show
  end

  # GET /ideal_outcomes/new
  def new
    @ideal_outcome = IdealOutcome.new
  end

  # GET /ideal_outcomes/1/edit
  def edit
  end

  # POST /ideal_outcomes
  # POST /ideal_outcomes.json
  def create
    @ideal_outcome = IdealOutcome.new(ideal_outcome_params)

    respond_to do |format|
      if @ideal_outcome.save
        format.html { redirect_to @ideal_outcome, notice: 'Ideal outcome was successfully created.' }
        format.json { render :show, status: :created, location: @ideal_outcome }
      else
        format.html { render :new }
        format.json { render json: @ideal_outcome.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideal_outcomes/1
  # PATCH/PUT /ideal_outcomes/1.json
  def update
    respond_to do |format|
      if @ideal_outcome.update(ideal_outcome_params)
        format.html { redirect_to @ideal_outcome, notice: 'Ideal outcome was successfully updated.' }
        format.json { render :show, status: :ok, location: @ideal_outcome }
      else
        format.html { render :edit }
        format.json { render json: @ideal_outcome.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideal_outcomes/1
  # DELETE /ideal_outcomes/1.json
  def destroy
    @ideal_outcome.destroy
    respond_to do |format|
      format.html { redirect_to ideal_outcomes_url, notice: 'Ideal outcome was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ideal_outcome
      @ideal_outcome = IdealOutcome.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ideal_outcome_params
      params.require(:ideal_outcome).permit(:new_situation_id, :recommended_decision_id)
    end
end

app/helpers/ideal_outcomes_helper.rb
module IdealOutcomesHelper
end

app/views/ideal_outcomes/_form.html.erb
<%= form_for(@ideal_outcome) do |f| %>
  <% if @ideal_outcome.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ideal_outcome.errors.count, "error") %> prohibited this ideal_outcome from being saved:</h2>

      <ul>
      <% @ideal_outcome.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :new_situation_id %><br>
    <%= f.text_field :new_situation_id %>
  </div>
  <div class="field">
    <%= f.label :recommended_decision_id %><br>
    <%= f.text_field :recommended_decision_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ideal_outcomes/edit.html.erb
<h1>Editing Ideal Outcome</h1>

<%= render 'form' %>

<%= link_to 'Show', @ideal_outcome %> |
<%= link_to 'Back', ideal_outcomes_path %>

app/views/ideal_outcomes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ideal Outcomes</h1>

<table>
  <thead>
    <tr>
      <th>New situation</th>
      <th>Recommended decision</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ideal_outcomes.each do |ideal_outcome| %>
      <tr>
        <td><%= ideal_outcome.new_situation %></td>
        <td><%= ideal_outcome.recommended_decision %></td>
        <td><%= link_to 'Show', ideal_outcome %></td>
        <td><%= link_to 'Edit', edit_ideal_outcome_path(ideal_outcome) %></td>
        <td><%= link_to 'Destroy', ideal_outcome, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ideal outcome', new_ideal_outcome_path %>

app/views/ideal_outcomes/new.html.erb
<h1>New Ideal Outcome</h1>

<%= render 'form' %>

<%= link_to 'Back', ideal_outcomes_path %>

app/views/ideal_outcomes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>New situation:</strong>
  <%= @ideal_outcome.new_situation %>
</p>

<p>
  <strong>Recommended decision:</strong>
  <%= @ideal_outcome.recommended_decision %>
</p>

<%= link_to 'Edit', edit_ideal_outcome_path(@ideal_outcome) %> |
<%= link_to 'Back', ideal_outcomes_path %>