config/routes.rb
Rails.application.routes.draw do
  resources :past_situations
  resources :new_situations
  resources :ideal_outcomes
  resources :past_outcomes
  resources :past_outcomes
  resources :recommended_decisions
  resources :user_decisions
  resources :new_situations
  resources :past_situations
  resources :users

end

app/models/recommended_decision.rb
class RecommendedDecision < ActiveRecord::Base
	has_many :ideal_outcomes
	has_many :new_situations, through: :ideal_outcomes
end

app/controllers/recommended_decisions_controller.rb
class RecommendedDecisionsController < ApplicationController
  before_action :set_recommended_decision, only: [:show, :edit, :update, :destroy]

  # GET /recommended_decisions
  # GET /recommended_decisions.json
  def index
    @recommended_decisions = RecommendedDecision.all
  end

  # GET /recommended_decisions/1
  # GET /recommended_decisions/1.json
  def show
  end

  # GET /recommended_decisions/new
  def new
    @recommended_decision = RecommendedDecision.new
  end

  # GET /recommended_decisions/1/edit
  def edit
  end

  # POST /recommended_decisions
  # POST /recommended_decisions.json
  def create
    @recommended_decision = RecommendedDecision.new(recommended_decision_params)

    respond_to do |format|
      if @recommended_decision.save
        format.html { redirect_to @recommended_decision, notice: 'Recommended decision was successfully created.' }
        format.json { render :show, status: :created, location: @recommended_decision }
      else
        format.html { render :new }
        format.json { render json: @recommended_decision.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recommended_decisions/1
  # PATCH/PUT /recommended_decisions/1.json
  def update
    respond_to do |format|
      if @recommended_decision.update(recommended_decision_params)
        format.html { redirect_to @recommended_decision, notice: 'Recommended decision was successfully updated.' }
        format.json { render :show, status: :ok, location: @recommended_decision }
      else
        format.html { render :edit }
        format.json { render json: @recommended_decision.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recommended_decisions/1
  # DELETE /recommended_decisions/1.json
  def destroy
    @recommended_decision.destroy
    respond_to do |format|
      format.html { redirect_to recommended_decisions_url, notice: 'Recommended decision was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recommended_decision
      @recommended_decision = RecommendedDecision.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recommended_decision_params
      params.require(:recommended_decision).permit(:content)
    end
end

app/helpers/recommended_decisions_helper.rb
module RecommendedDecisionsHelper
end

app/views/recommended_decisions/_form.html.erb
<%= form_for(@recommended_decision) do |f| %>
  <% if @recommended_decision.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recommended_decision.errors.count, "error") %> prohibited this recommended_decision from being saved:</h2>

      <ul>
      <% @recommended_decision.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recommended_decisions/edit.html.erb
<h1>Editing Recommended Decision</h1>

<%= render 'form' %>

<%= link_to 'Show', @recommended_decision %> |
<%= link_to 'Back', recommended_decisions_path %>

app/views/recommended_decisions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Recommended Decisions</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recommended_decisions.each do |recommended_decision| %>
      <tr>
        <td><%= recommended_decision.content %></td>
        <td><%= link_to 'Show', recommended_decision %></td>
        <td><%= link_to 'Edit', edit_recommended_decision_path(recommended_decision) %></td>
        <td><%= link_to 'Destroy', recommended_decision, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recommended decision', new_recommended_decision_path %>

app/views/recommended_decisions/new.html.erb
<h1>New Recommended Decision</h1>

<%= render 'form' %>

<%= link_to 'Back', recommended_decisions_path %>

app/views/recommended_decisions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @recommended_decision.content %>
</p>

<%= link_to 'Edit', edit_recommended_decision_path(@recommended_decision) %> |
<%= link_to 'Back', recommended_decisions_path %>