config/routes.rb
Rails.application.routes.draw do
  resources :past_situations
  resources :new_situations
  resources :ideal_outcomes
  resources :past_outcomes
  resources :past_outcomes
  resources :recommended_decisions
  resources :user_decisions
  resources :new_situations
  resources :past_situations
  resources :users

end

app/models/past_situation.rb
class PastSituation < ActiveRecord::Base
  belongs_to :user
  has_many :tags, as: :taggable
  has_many :past_outcomes
  has_many :user_decisions, through: :past_outcomes
end

app/controllers/past_situations_controller.rb
class PastSituationsController < ApplicationController
  before_action :set_past_situation, only: [:show, :edit, :update, :destroy]

  # GET /past_situations
  # GET /past_situations.json
  def index
    @past_situations = PastSituation.all
  end

  # GET /past_situations/1
  # GET /past_situations/1.json
  def show
  end

  # GET /past_situations/new
  def new
    @past_situation = PastSituation.new
  end

  # GET /past_situations/1/edit
  def edit
  end

  # POST /past_situations
  # POST /past_situations.json
  def create
    @past_situation = PastSituation.new(past_situation_params)

    respond_to do |format|
      if @past_situation.save
        format.html { redirect_to @past_situation, notice: 'Past situation was successfully created.' }
        format.json { render :show, status: :created, location: @past_situation }
      else
        format.html { render :new }
        format.json { render json: @past_situation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /past_situations/1
  # PATCH/PUT /past_situations/1.json
  def update
    respond_to do |format|
      if @past_situation.update(past_situation_params)
        format.html { redirect_to @past_situation, notice: 'Past situation was successfully updated.' }
        format.json { render :show, status: :ok, location: @past_situation }
      else
        format.html { render :edit }
        format.json { render json: @past_situation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /past_situations/1
  # DELETE /past_situations/1.json
  def destroy
    @past_situation.destroy
    respond_to do |format|
      format.html { redirect_to past_situations_url, notice: 'Past situation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_past_situation
      @past_situation = PastSituation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def past_situation_params
      params.require(:past_situation).permit(:description, :user_id)
    end
end

app/helpers/past_situations_helper.rb
module PastSituationsHelper
end

app/views/past_situations/_form.html.erb
<%= form_for(@past_situation) do |f| %>
  <% if @past_situation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@past_situation.errors.count, "error") %> prohibited this past_situation from being saved:</h2>

      <ul>
      <% @past_situation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/past_situations/edit.html.erb
<h1>Editing Past Situation</h1>

<%= render 'form' %>

<%= link_to 'Show', @past_situation %> |
<%= link_to 'Back', past_situations_path %>

app/views/past_situations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Past Situations</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @past_situations.each do |past_situation| %>
      <tr>
        <td><%= past_situation.description %></td>
        <td><%= past_situation.user %></td>
        <td><%= link_to 'Show', past_situation %></td>
        <td><%= link_to 'Edit', edit_past_situation_path(past_situation) %></td>
        <td><%= link_to 'Destroy', past_situation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Past situation', new_past_situation_path %>

app/views/past_situations/new.html.erb
<h1>New Past Situation</h1>

<%= render 'form' %>

<%= link_to 'Back', past_situations_path %>

app/views/past_situations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @past_situation.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @past_situation.user %>
</p>

<%= link_to 'Edit', edit_past_situation_path(@past_situation) %> |
<%= link_to 'Back', past_situations_path %>