config/routes.rb
Rails.application.routes.draw do
  resources :past_situations
  resources :new_situations
  resources :ideal_outcomes
  resources :past_outcomes
  resources :past_outcomes
  resources :recommended_decisions
  resources :user_decisions
  resources :new_situations
  resources :past_situations
  resources :users

end

app/models/user_decision.rb
class UserDecision < ActiveRecord::Base
	has_many :past_outcomes
	has_many :past_situations, through: :past_outcomes
end

app/controllers/user_decisions_controller.rb
class UserDecisionsController < ApplicationController
  before_action :set_user_decision, only: [:show, :edit, :update, :destroy]

  # GET /user_decisions
  # GET /user_decisions.json
  def index
    @user_decisions = UserDecision.all
  end

  # GET /user_decisions/1
  # GET /user_decisions/1.json
  def show
  end

  # GET /user_decisions/new
  def new
    @user_decision = UserDecision.new
  end

  # GET /user_decisions/1/edit
  def edit
  end

  # POST /user_decisions
  # POST /user_decisions.json
  def create
    @user_decision = UserDecision.new(user_decision_params)

    respond_to do |format|
      if @user_decision.save
        format.html { redirect_to @user_decision, notice: 'User decision was successfully created.' }
        format.json { render :show, status: :created, location: @user_decision }
      else
        format.html { render :new }
        format.json { render json: @user_decision.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_decisions/1
  # PATCH/PUT /user_decisions/1.json
  def update
    respond_to do |format|
      if @user_decision.update(user_decision_params)
        format.html { redirect_to @user_decision, notice: 'User decision was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_decision }
      else
        format.html { render :edit }
        format.json { render json: @user_decision.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_decisions/1
  # DELETE /user_decisions/1.json
  def destroy
    @user_decision.destroy
    respond_to do |format|
      format.html { redirect_to user_decisions_url, notice: 'User decision was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_decision
      @user_decision = UserDecision.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_decision_params
      params.require(:user_decision).permit(:choice)
    end
end

app/helpers/user_decisions_helper.rb
module UserDecisionsHelper
end

app/views/user_decisions/_form.html.erb
<%= form_for(@user_decision) do |f| %>
  <% if @user_decision.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_decision.errors.count, "error") %> prohibited this user_decision from being saved:</h2>

      <ul>
      <% @user_decision.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :choice %><br>
    <%= f.text_field :choice %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_decisions/edit.html.erb
<h1>Editing User Decision</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_decision %> |
<%= link_to 'Back', user_decisions_path %>

app/views/user_decisions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing User Decisions</h1>

<table>
  <thead>
    <tr>
      <th>Choice</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_decisions.each do |user_decision| %>
      <tr>
        <td><%= user_decision.choice %></td>
        <td><%= link_to 'Show', user_decision %></td>
        <td><%= link_to 'Edit', edit_user_decision_path(user_decision) %></td>
        <td><%= link_to 'Destroy', user_decision, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User decision', new_user_decision_path %>

app/views/user_decisions/new.html.erb
<h1>New User Decision</h1>

<%= render 'form' %>

<%= link_to 'Back', user_decisions_path %>

app/views/user_decisions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Choice:</strong>
  <%= @user_decision.choice %>
</p>

<%= link_to 'Edit', edit_user_decision_path(@user_decision) %> |
<%= link_to 'Back', user_decisions_path %>